#
#  Author: Hari Sekhon
#  Date: 2019-10-21 17:24:53 +0100 (Mon, 21 Oct 2019)
#
#  vim:ts=4:sts=4:sw=4:noet
#
#  https://github.com/HariSekhon/Dockerfiles
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

REPO := harisekhon/fakes3

include ../Makefile.in

MAP_PORTS := 4567
