#!/usr/bin/env bash
#  vim:ts=4:sts=4:sw=4:et
#
#  Author: Hari Sekhon
#  Date: 2017-09-13 14:47:28 +0200 (Wed, 13 Sep 2017)
#
#  https://github.com/harisekhon/Dockerfiles
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/harisekhon
#

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x
srcdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# DockerHub will always build latest from master, so find out what the latest tag is and tag this build as such

IMAGE_NAME="${IMAGE_NAME:-$(awk -F= '/^REPO=/{print $2}' "$srcdir/../Makefile")}"
DOCKER_REPO="${DOCKER_REPO:-${IMAGE_NAME/:*}}"

# There is a race condition here between the time we call get_presto_versions.sh in Dockerfile to do the build and
# calling it again here to get the latest version, Facebook could potentially publish a new build in the interim
# which would result in an incorrect tagging until the next run
latest_tag="$("$srcdir/../get_presto_versions.sh" | head -n1)"

docker tag "$DOCKER_IMAGE" "$DOCKER_REPO:$tag"
docker push "$DOCKER_REPO:$tag"
