#
#  Author: Hari Sekhon
#  Date: 2021-11-05 03:35:32 +0000 (Fri, 05 Nov 2021)
#
#  vim:ts=4:sts=4:sw=4:noet
#
#  https://github.com/HariSekhon/Dockerfiles
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

REPO := harisekhon/circleci-runner

include ../Makefile.in
