#
#  Author: Hari Sekhon
#  Date: 2018-01-30 16:15:34 +0000 (Tue, 30 Jan 2018)
#
#  vim:ts=4:sts=4:sw=4:noet
#
#  https://github.com/HariSekhon/Dockerfiles
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

REPO := harisekhon/tcollector

# Makefile.in assumes to drop in to bash if no ports mapped, set NOPORTS explicitly instead of redefining run and run-foreground targets
NOPORTS := 1

include ../Makefile.in

#.PHONY: run
#run:
#	docker run -ti $(REPO_TAG)
#
#.PHONY: run-foreground
#run-foreground:
#	docker run $(REPO_TAG)
