#
#  Author: Hari Sekhon
#  Date: 2017-08-22 14:16:43 +0200 (Tue, 22 Aug 2017)
#
#  vim:ts=4:sts=4:sw=4:noet
#
#  https://github.com/HariSekhon/Dockerfiles
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

REPO := harisekhon/superset

include ../Makefile.in

MAP_PORTS := 8088
