#
#  Author: Hari Sekhon
#  Date: 2018-01-29 18:08:56 +0000 (Mon, 29 Jan 2018)
#
#  vim:ts=4:sts=4:sw=4:noet
#
#  https://github.com/HariSekhon/Dockerfiles
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

REPO := harisekhon/collectd

MAP_PORTS := 9103

include ../Makefile.in
