#
#  Author: Hari Sekhon
#  Date: 2020-02-08 22:53:37 +0000 (Sat, 08 Feb 2020)
#
#  vim:ts=4:sts=4:sw=4:noet
#
#  https://github.com/HariSekhon/Dockerfiles
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

REPO := harisekhon/awless

RUN_ARGS := --help

include ../Makefile.in
