#
#  Author: Hari Sekhon
#  Date: 2022-01-20 15:00:07 +0000 (Thu, 20 Jan 2022)
#
#  vim:ts=4:sts=4:sw=4:et
#
#  https://github.com/harisekhon/Dockerfiles
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/harisekhon
#

FROM jenkins/jenkins:lts

RUN /bin/jenkins-plugin-cli --plugins workflow-aggregator:2.6
