#!/usr/bin/env bash
#
#  vim:ts=4:sts=4:sw=4:et
#
#  Author: Hari Sekhon
#  Date: 2021-11-05 03:32:58 +0000 (Fri, 05 Nov 2021)
#
#  https://github.com/HariSekhon/Dockerfiles
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# Get list of versions to be used by tests/check_for_new_version

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x

get_versions(){
    curl https://api.github.com/repos/actions/runner/releases -sS --fail |
    jq -r '.[].name'
}

get_versions
