#
#  Author: Hari Sekhon
#  Date: 2021-12-06 16:44:11 +0000 (Mon, 06 Dec 2021)
#
#  vim:ts=4:sts=4:sw=4:noet
#
#  https://github.com/HariSekhon/Dockerfiles
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

REPO := harisekhon/git-kustomize

include ../Makefile.in
